name: prefect-cli
author: sp1thas
description: Run prefect commands on a Python project
branding:
  icon: check
  color: blue

inputs:
  api-key:
    description: A Prefect Cloud API key.
    required: true
  command:
    description: A prefect command.
    required: true
  prefect-version:
    description: Version of prefect to use
    required: false
    default: ""
  requirements-files:
    description:
      path(s) to requirements files that should be installed to properly
      configure third-party imports
    required: false
    default: ""

outputs:
  prefect-command:
    description: prefect command result
    value: ${{ steps.run-prefect-command.outputs.prefect-command-result }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/bin/ensure_python
      shell: bash
    - run:
        ${{ github.action_path }}/bin/install_packages ${{ inputs.prefect-version }} ${{ inputs.requirements-files }}
      shell: bash
    - id: run-prefect-command
      run:
        ${{ github.action_path }}/bin/run_prefect ${{ inputs.command }}
      shell: bash