name: python-prefect
author: sp1thas
description: Run prefect commands on a Python project
branding:
  icon: check
  color: blue

inputs:
  api-key:
    description: A Prefect Cloud API key.
    required: true
  project-name:
    description: The name of the Prefect project to register this flow in
    required: true
  prefect-version:
    description: Version of prefect to use
    required: false
    default: ""
  flow-path:
    description: A path to a file or a directory containing the flow(s) to register.
    required: false
    default: ""
  flow-module-path:
    description: A python module name containing the flow(s) to register.
    required: false
    default: ""
  json-path:
    description: A path or URL to a JSON file created by `prefect build` containing the flow(s) to register.
    required: false
    default: ""
  flow-name:
    description:
      The name of a flow to register from the specified paths/modules.
      If provided, only flows with a matching name will be registered.
    required: false
    default: ""
  flow-label:
    description: A label to add on all registered flow(s).
    required: false
    default: ""
  requirements-files:
    description:
      path(s) to requirements files that should be installed to properly
      configure third-party imports
    required: false
    default: ""

outputs:
  prefect-login:
    description: prefect login result
    value: ${{ steps.run-prefect-login.outputs.prefect-output }}
  prefect-register:
    description: prefect register result
    value: ${{ steps.run-prefect-register.outputs.prefect-output }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/bin/ensure_python
      shell: bash
    - run:
        ${{ github.action_path }}/bin/install_packages ${{ inputs.prefect-version }} ${{ inputs.requirements-files }}
      shell: bash
    - id: run-prefect-login
      run:
        ${{ github.action_path }}/bin/run_login ${{ inputs.api-key }}
      shell: bash
    - id: run-prefect-register
      run:
        ${{ github.action_path }}/bin/run_register ${{ inputs.project-name }} ${{ inputs.flow-path }} ${{ inputs.flow-module-path }} ${{ inputs.json-path }} ${{ inputs.flow-name }} ${{ inputs.flow-label }}
      shell: bash